export type NotificationType =
  | "goal_achieved"
  | "checkin_submitted"
  | "support_ticket_created"
  | "support_ticket_updated"
  | "support_ticket_comment_added"
  | "support_ticket_comment_edited"
  | "support_ticket_comment_deleted"
  | "support_ticket_status_changed"
  | "support_ticket_closed"
  | "support_ticket_reopened"
  | "meal_reminder"
  | "health_checkin_reminder"
  | "goal_checkin_reminder"
  | "cycle_reminder"
  | "pregnancy_checkin";
